spring:
  application:
    name: aiservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitness-activity
      database: fitness-activity

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true
      hostname: localhost

logging:
  level:
    org.springframework.web: DEBUG

rabbitmq:
  queue: activity-queue
  exchange: fitness-exchange
  routing-key: activity-routing-key

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}