spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:8181/realms/fitness-oauth2-realm/protocol/openid-connect/certs
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: userservice
              uri: lb://USERSERVICE
              predicates:
                - Path=/api/users/**

            - id: activityservice
              uri: lb://ACTIVITYSERVICE
              predicates:
                - Path=/api/activities
                - Path=/api/activities/**

            - id: aiservice
              uri: lb://AISERVICE
              predicates:
                - Path=/api/recommendations/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost

server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG